nav:
  - Home: 
    - vLLM x Intel Gaudi: README.md
    - Getting Started:
      - getting_started/quickstart.md
      - getting_started/installation.md
    - Quick Links:
      - User Guide: user_guide/README.md
      - Developer Guide: dev_guide/README.md
      - API Reference: api/README.md
  - User Guide:
    - Summary: user_guide/README.md
    - user_guide/v1_guide.md
    - General:
      - user_guide/*
    - Configuration:
      - Summary: configuration/README.md
      - configuration/*
    - Models:
      - models/validated_models.md
    - Features:
      - features/supported_features.md
      - features/compatibility_matrix.md
      - features/*
      - features/quantization
  - Developer Guide:
    - Summary: dev_guide/README.md
    - General:
      - glob: dev_guide/*
        flatten_single_child_sections: true
    - Design Documents:
      - design/*
  - API Reference:
    - Summary: api/README.md
    - Contents:
      - glob: api/vllm_hpu/*
        preserve_directory_names: true